config/routes.rb
Rails.application.routes.draw do
  # root 'sessions#index'
  # root 'user_organizations#index'

  root 'welcome#index'

  resources :organizations
  resources :users
  resources :sessions
  resources :reviews
  resources :restaurants
  resources :plans

  resources :cuisines

  get 'login', :to => 'sessions#new'
  delete 'logout', :to => 'sessions#destroy'
  get 'signup', :to => 'users#new'
  get 'logged_in', :to => 'sessions#index'
  get 'join', :to => 'users#join'
  get '/:id/join-plan', :to => 'plans#join_plan', :as => 'join-plan'
  delete '/:id/leave_plan', :to => 'plans#leave_plan', :as => 'leave-plan'
  get 'add', :to => 'users#add'
  post 'join/', :to => 'users#join'
  get 'dashboard/', :to =>'users#dashboard'
  get '/:token/confirm_email/:id', :to => "organizations#confirm_email", as: '/confirm_email'
  delete '/:id/remove-user/:organization', :to => 'organizations#remove_user', :as => 'remove_user'
  post 'request_access/:id', :to => "users#request_access", as: "request_access"
  get '/:token/grant_access/:id', :to => "organizations#grant_access", as: '/grant_access'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :user_organizations
  has_many :organizations, through: :user_organizations
  has_many :reviews
  has_many :plans_users
  has_many :plans, through: :plans_users
  # has_many :plans, foreign_key: :host_id STEVEN'S NOTES
  has_many :hostings, foreign_key: :host_id, class_name: Plan 
  has_many :restaurants, through: :reviews
  has_many :cuisines
  has_secure_password
  validates_uniqueness_of :email
  validates_presence_of :name, :email
  validates :password, :presence => true,
                       :length => {:within => 6..20}

  has_attached_file :avatar,
    styles: { thumb: "30x30", small: "64x64", med: "100x100", large: "200x200" },
    :default_url => 'default_:style.png'
  validates_attachment :avatar,
    content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] },
    size: { in: 0..100.kilobytes }


    def domain_name
      self.email.gsub(/.+@([^.]+.+)/, '\1')
    end

    def set_confirmation_token
      if self.confirm_token.blank?
         self.confirm_token = SecureRandom.urlsafe_base64.to_s
      end
    end

    def is_member?(organization)
      self.organizations.include?(organization)
    end

    def is_admin?(organization)
      user_organization = UserOrganization.find_by(organization_id: organization.id)
      user_organization.admin
    end


    private
    def email_activate
      self.email_confirmed = true
      self.confirm_token = nil
    end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authorize, only: [:new, :create, :join]
  before_action :set_user, only: [:show, :edit]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to dashboard_path, :notice => "Thank you for signing up!"
    else
      render :new
    end
  end

  def join
    user_domain = current_user.domain_name
    organization = Organization.find(params[:user][:organizations])
    domains = organization.domain_names
    if domains.include?(user_domain) && !organization.users.include?(current_user)
      current_user.set_confirmation_token
      current_user.save(validate: false)
      UserMailer.registration_confirmation(current_user, organization.id).deliver_now
      flash[:success] = "Please confirm your email address to continue"
      redirect_to dashboard_path
    else
      flash[:error] = "In order to join this group you must have"
        @organization = Organization.find(params[:user][:organizations])
        @user = current_user
        render 'join_request'
      end
    end

  def add
    @user = current_user
  end

  def request_access
    organization = Organization.find(params[:id])
    current_user.set_confirmation_token
    current_user.save(validate: false)
    UserMailer.request_access(organization.admin_emails, current_user, organization.id).deliver_now
    redirect_to dashboard_path
    flash[:success] = "Waiting for Admin to Grant Access. Hold Tight"
  end

  def dashboard
    # @user = User.find(params[:id])
    @user = current_user
  end

  def edit
    # @plan = Plan.find(params[:id])
    user = User.find(params[:id])
    # binding.pry
  end

  def update
    user = User.find(params[:id])
    # binding.pry
    if user.update_attributes(user_params)
      redirect_to user, :notice => "Your settings have been updated!"
    else
      render 'edit'
    end
  end

  private
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :position, :bio, :password, :password_confirmation, :email, :avatar)
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/users/_form.html.erb
  <%= form_for(user) do |f| %>
      <% if user.errors.any? %>
        <div id = "error_explanation">
          <h2> <%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>
          <ul>
            <% user.errors.full_messages.each do |msg| %>
              <li><%= msg %> </li>
            <% end %>
          </ul>
        </div>
      <% end %>

    <div class="form-field-wrapper">
      <div class = "name">
        <%= f.label :name %>
        <%= f.text_field :name, :class => 'input-sm form-full' %>
      </div>
    </div>

    <% if logged_in? %>
      <div class="form-field-wrapper">
        <div class = "avatar">
          <%= f.label :avatar %>
          <%= f.file_field :avatar, :class => 'input-sm form-full' %>
        </div>
      </div>
    <%end%>

    <div class="form-field-wrapper">
      <div class = "email">
        <%= f.label :email %>
        <%= f.text_field :email, :id => 'signup-email', :class => 'input-sm form-full' %>
      </div>
    </div>

    <% if logged_in? %>
      <div class="form-field-wrapper">
        <div class = "position">
          <%= f.label :position %>
          <%= f.text_field :position, :class => 'input-sm form-full' %>
        </div>
      </div>
    <%end%>

    <% if logged_in? %>
      <div class="form-field-wrapper">
        <div class = "bio">
          <%= f.label :bio %>
          <%= f.text_area :bio, :class => 'input-sm form-full' %>
        </div>
      </div>
    <%end%>

    <div class="form-field-wrapper">
      <div class = "password">
        <%= f.label :password %>
        <%= f.password_field :password, :class => 'input-sm form-full' %>
      </div>
    </div>

    <div class="form-field-wrapper">
      <div class = "password_confirmation">
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation, :class => 'input-sm form-full' %>
      </div>
    </div>

      <div class= "actions">
        <%= f.submit "submit", :class => 'btn btn-md btn-black' %>
      </div>
  <% end %>

app/views/users/add.html.erb
<h1>Join existing group.</h1>


<p>Put a form here with dropdown email extension and email input field</p>


<%= form_for(@user, method:"post", url:join_path) do |f| %>
  <div class = "organization-dropdown-field"> <%= f.label :organizations %>
   <%= f.collection_select :organizations, Organization.all, :id, :name %>
  </div>
  <%= f.submit "Join Organization" %>
<% end %>

<% if flash[:success]  %>
<%= flash[:success]  %>

<% end %>

app/views/users/dashboard.html.erb
       <!-- CONTENT --------------------------------------------------------------------------------->

       



                       <!-- Pricing Table Section -->
                        <%= flash[:success] %>

                        <section class="ptb-sm-80">
                            <div class="container text-center col-md-12">
                                <div class="row">
                                    <h3>My Dashboard</h3>
                                    <p class="lead col-md-8 col-md-offset-2"><%= link_to "Public bio", user_path(current_user) %></p>
                                </div>
                                <div class="spacer-60"></div>
                                <div class="row">
                                    <div class="col-md-4 mb-30">
                                        <div class="Pricing-box">
                                            <div class="price-title spacing-box">
                                                <h4>Upcoming Plans</h4>
                                            </div>
                                            <hr />
                                            <div class="pricing-features spacing-grid">
                                              <% @user.plans.each do |plan| %>
                                                <ul>
                                                  <li><%= link_to "#{plan.name}", plan_path(plan.id) %></li>
                                                </ul>
                                              <%end%>
                                            </div>
                                            <hr />
                                            <div class="spacing-grid">
                                                <a class="btn btn-md btn-blue">Make a new plan</a>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-4 mb-30">
                                        <div class="Pricing-box highlight">
                                            <div class="price-title spacing-box">
                                                <h4>Your Organizations</h4>
                                            </div>
                                            <hr />
                                            <div class="pricing-features spacing-grid">
                                              <% @user.organizations.each do |organization| %>
                                                <ul>
                                                  <li><%= link_to "#{organization.name}", organization_path(organization.id) %></li>
                                                </ul>
                                              <%end%>
                                            </div>
                                            <hr />
                                            <div class="spacing-grid">
                                                <%= link_to "Make an Organization", new_organization_path, :class => "btn btn-md btn-blue" %>
                                                <div style="height:15px;"></div>
                                                <%= link_to "Join an Organization", add_path, :class => "btn btn-md btn-blue" %>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-4 mb-30">
                                        <div class="Pricing-box">
                                            <div class="price-title spacing-box">
                                                <h4>Your Reviews</h4>
                                            </div>
                                            <hr />
                                            <div class="pricing-features spacing-grid">
                                              <% @user.restaurants.each do |restaurant| %>
                                                <ul>
                                                  <li><%= link_to "#{restaurant.name}", restaurant_path(restaurant.id) %></li>
                                                </ul>
                                              <%end%>
                                            </div>
                                            <hr />
                                            <div class="spacing-grid">
                                                <a class="btn btn-md btn-blue">Write a new review</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                </div>
                                </div>
                            </div>
                        </section>
                      <!-- End Pricing Table Section -->
                    </div><!--END "col-md-9" SECTION -->
                </div>

            </div>
        </section>
        <!-- End Sidebar Section -->

        <!-- End CONTENT ------------------------------------------------------------------------------>

app/views/users/edit.html.erb
<h1>Edit User</h1>
<%= render 'form', {user: User.find(params[:id])} %>

app/views/users/index.html.erb
<% @users.each do |user| %>
<%= user.id %>
<% end %>

app/views/users/join_request.html.erb
<p>
  Join this group by using one of the following domains
  or request access
  <% @organization.domains.each do |name| %>
  <ul>
    <li><%= name %></li>
  </ul>
  <% end %>

  <%#= form_for(@user, method: :post, url: join_path) do |f| %>
    <%#= f.label :email %>
    <%#= f.text_field :email, placeholder: "name@domain.com" %>
    <%#= f.submit "Join" %>
  <%#end %>

  <br>
  <%= link_to("Request Access from admin", request_access_path(@organization), method: :post) %>
</p>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= render 'form', {user: @user}%>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>

<h2>Position:</h2><%= @user.position %>
<h2>Bio:</h2><%= @user.bio %>