config/routes.rb
Rails.application.routes.draw do
  # root 'sessions#index'
  # root 'user_organizations#index'

  root 'welcome#index'

  resources :organizations
  resources :users
  resources :sessions
  resources :reviews
  resources :restaurants
  resources :plans

  resources :cuisines

  get 'login', :to => 'sessions#new'
  delete 'logout', :to => 'sessions#destroy'
  get 'signup', :to => 'users#new'
  get 'logged_in', :to => 'sessions#index'
  get 'join', :to => 'users#join'
  get '/:id/join-plan', :to => 'plans#join_plan', :as => 'join-plan'
  delete '/:id/leave_plan', :to => 'plans#leave_plan', :as => 'leave-plan'
  get 'add', :to => 'users#add'
  post 'join/', :to => 'users#join'
  get 'dashboard/', :to =>'users#dashboard'
  get '/:token/confirm_email/:id', :to => "organizations#confirm_email", as: '/confirm_email'
  delete '/:id/remove-user/:organization', :to => 'organizations#remove_user', :as => 'remove_user'
  post 'request_access/:id', :to => "users#request_access", as: "request_access"
  get '/:token/grant_access/:id', :to => "organizations#grant_access", as: '/grant_access'

end

app/models/organization.rb
class Organization < ActiveRecord::Base
  has_many :user_organizations
  has_many :users, through: :user_organizations
  has_many :plans, through: :users

  has_many :restaurants, through: :users

  validates_presence_of :name

  has_attached_file :logo,
  styles: { :large => "300x" },
  :default_url => 'defaultlogo_:style.png'
  validates_attachment :logo,
  content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] },
  size: { in: 0..100.kilobytes }

  def domain_names
    self.domains.join(", ")
  end

  def domain_names=(domain_names)
    self.domains.split(",")
  end


  def admins
    admins = self.user_organizations.where(admin: "true")
    admins.map { |admin| admin.user_id}
  end

  def admin_emails
    self.admins.map do |id|
      admin = User.find(id)
      admin.email
    end
  end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController

  # before_action :is_member?, only: [:join, :show, :edit, :update]

  skip_before_action :authorize, only: [:new, :create]

  def index
    @organizations = Organization.all
  end

  def new
    @organization = Organization.new
  end

  def confirm_email
    user = User.find_by_confirm_token(params[:token])
    organization = Organization.find(params[:id])
    if user
       user.send('email_activate')
       user.save(validate: false)
       organization.users << user
       redirect_to organization_path
    else
      flash[:error] = "Sorry. User does not exist"
      redirect_to root_url
    end
  end

  def grant_access
    user = User.find_by_confirm_token(params[:token])
    organization = Organization.find(params[:id])
    if user
       user.send('email_activate')
       user.save(validate: false)
       organization.users << user
       redirect_to organization_path
    else
      flash[:error] = "Sorry. User does not exist"
      redirect_to root_url
    end
  end

  def create
    @organization = Organization.create(org_params)
    current_user.organizations << @organization
    user_organization = current_user.user_organizations.find_by(organization_id: @organization.id)
    @organization.domains << params[:organization][:domains]
    user_organization.update(admin: true)
    flash[:notice] = "You just created a group! You are now the admin."
    redirect_to @organization
  end

  def show
    @organization = Organization.find(params[:id])
    @plans = Plan.all
    # redirect_to '/organizations/@organization.name'
  end

  def edit
    @organization = Organization.find(params[:id])
  end

  def remove_user
    @organization = Organization.find(params[:organization])
    @user = User.find(params[:id])
    @organization.users.destroy(@user)
    redirect_to @organization
  end

  def update
    current_organization = Organization.find(params[:id])
    current_organization.domains = params[:organization][:domains].split(", ")
    current_organization.update_attributes(org_params)
    current_organization.save
    redirect_to current_organization
  end

  private

  def org_params
    params.require(:organization).permit(:name, :location, :logo, :domain_names)
  end

end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/views/organizations/_form.html.erb
<%= form_for (@organization) do |f| %>
<div class="name-field">
  <%= f.label :name %>
  <%= f.text_field :name %>
</div>

<div class="location-field">
  <%= f.label :location %>
  <%= f.text_field :location %>
</div>

<div class="logo-field">
  <%= f.label :logo %>
  <%= f.file_field :logo %>
</div>

<div class="domain-field">
  <%= f.label :domains, "Acceptable Domain" %>
  <%= f.text_field :domains, placeholder:"e.g. @flatironschool.com" %>
</div>

<%= f.submit %>
<% end %>

app/views/organizations/_organization.html.erb
                        <section class="ptb ptb-sm-80">
                            <div class="container text-center col-md-12">
                                    <div class="row">
                                                <div class="col-md-3 col-sm-4 mt-xs-30">
                                                    <%= render "plans/form", {plan: Plan.new } %>
                                                    <%= render "plans/all_plans", {plans: @plans} %>
                                                </div>
                                                <div class="col-md-9 mb-30">
                                                    <% @organization.restaurants.each do |restaurant| %>
                                                        <div class="Pricing-box highlight">
                                                            <div class="price-title spacing-box">
                                                                <h3> <%= link_to restaurant.name, restaurant_path(restaurant) %></h3>
                                                            </div>
                                                            <hr />
                                                            <div class="pricing-features spacing-grid">
                                                              <ul>
                                                                <h4>Details</h4>
                                                                    <li>Location: <%= restaurant.address %></li>
                                                                    <!-- <li>Cuisine: <%#= restaurant.cuisine.name %></li> -->
                                                                    <li>Average Wait Time: <%= restaurant.average("wait_time") %> minutes</li>
                                                                    <li>Average Rating: <%= restaurant.average("rating") %>/5 </li>
                                                                    <li>Average Price: $<%= restaurant.average("price") %> </li>
                                                                      <h4>Most Recent Review</h4>
                                                                    <li>"<%= restaurant.reviews.last.comment %>"</li>
                                                              </ul>
                                                            </div>
                                                        </div>
                                                    <% end  %>
                                                    <br>
                                                    <p>Click <%= link_to "here", new_restaurant_path %> to add a Restaurant to this Organization</p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                </div>
                            </div>
                        </section>
                      <!-- End Pricing Table Section -->
                    </div><!--END "col-md-9" SECTION -->
                </div>
            </div>
        </section>

app/views/organizations/edit.html.erb
<% if current_user.is_admin?(@organization) %>
  <h1>Edit your form here:</h1>
  <%= render 'form' %>
<% else %>
  <h4>Sorry! You must be an admin to edit this organization.</h4>
<% end %>

app/views/organizations/index.html.erb
<h1>All organizations</h1>
<% @organizations.each do |organization| %>
  <ul>
    <li><%= link_to "#{organization.name}", organization_path(organization.id) %></li>
  </ul>
<% end  %>

app/views/organizations/new.html.erb
<h1>This is a new organization form</h1>

<%= render 'form' %>    

app/views/organizations/remove_user.js.erb
alert("all the javascript")

app/views/organizations/show.html.erb
<!-- 
<body class="full-intro"> -->




        <!-- Intro Section -->
    
        <section class="inner-intro bg-img2 overlay-dark parallax parallax-background2">
            <div class="container">
                <div class="row title">
                    <%= image_tag @organization.logo.url(:large) %>
                    <h1 class="h1 light-color">What's for Lunch at <%= @organization.name %>?</h1>
                </div>
            </div>
        </section>
        <div class="clearfix"></div>
        <!-- End Intro Section -->




      <% if current_user.is_member?(@organization) %>
        <%= render @organization %>
      <% else  %>
        "You must be part of this organization to view it"
      <%end%>
        