config/routes.rb
Rails.application.routes.draw do
  # root 'sessions#index'
  # root 'user_organizations#index'

  root 'welcome#index'

  resources :organizations
  resources :users
  resources :sessions
  resources :reviews
  resources :restaurants
  resources :plans

  resources :cuisines

  get 'login', :to => 'sessions#new'
  delete 'logout', :to => 'sessions#destroy'
  get 'signup', :to => 'users#new'
  get 'logged_in', :to => 'sessions#index'
  get 'join', :to => 'users#join'
  get '/:id/join-plan', :to => 'plans#join_plan', :as => 'join-plan'
  delete '/:id/leave_plan', :to => 'plans#leave_plan', :as => 'leave-plan'
  get 'add', :to => 'users#add'
  post 'join/', :to => 'users#join'
  get 'dashboard/', :to =>'users#dashboard'
  get '/:token/confirm_email/:id', :to => "organizations#confirm_email", as: '/confirm_email'
  delete '/:id/remove-user/:organization', :to => 'organizations#remove_user', :as => 'remove_user'
  post 'request_access/:id', :to => "users#request_access", as: "request_access"
  get '/:token/grant_access/:id', :to => "organizations#grant_access", as: '/grant_access'

end

app/models/plan.rb
class Plan < ActiveRecord::Base
  has_many :plans_users
  has_many :users, through: :plans_users
  belongs_to :restaurant
  belongs_to :organization
  belongs_to :host, class_name: User
  #validates_presence_of :time, :date, :restaurant
  #validates :user, uniqueness: true
  #validates :user, uniqueness: {message: "already in the plan"}


  def pretty_time
    @plan.time.strftime("%B %d at %I:%M %p")
  end

  # def todays_date?
  #   if Time.zone.today == params[:date]
  #   datetime = DateTime.now
  #   datetime.today?
  #   end

  # end

end

app/controllers/plans_controller.rb
class PlansController < ApplicationController

  def new
    @plan = Plan.new
  end


  def create
    @plan = Plan.create(plan_params)
    @plan.host = current_user
    @plan.users << current_user
    @plan.save
    redirect_to @plan
  end


  def index
    @plans = Plan.all
     respond_to do |format|
      format.html
      format.js {}
    end
  end

  def show
    @plan = Plan.find(params[:id])
    @restaurant = @plan.restaurant
    @hash = Gmaps4rails.build_markers (@restaurant) do |restaurant, marker|
     marker.lat restaurant.latitude
     marker.lng restaurant.longitude
   end
  end

  def leave_plan
    @plan = Plan.find(params[:id])
    @plan.users.delete(current_user)
    @plan.users
    @plan.save
    @in_plan = @plan.users.include?(current_user)
    respond_to do |format|
      format.html
      format.js {}
    end
  end

  def join_plan
    @plan = Plan.find(params[:id])

    if !@plan.users.include?(current_user)
      @plan.users << current_user
      @plan.save
    else

      flash[:error] = "You are already participating in this plan."
    end


    @in_plan = @plan.users.include?(current_user)



    respond_to do |format|
      format.html
      format.js {}
    end
  end


  # if user
  #      user.send('email_activate')
  #      user.save(validate: false)
  #      organization.users << user
  #      redirect_to organization_path
  #   else
  #     flash[:error] = "Sorry. User does not exist"
  #     redirect_to root_url
  #   end





  def edit
    @plan = Plan.find(params[:id])
  end

  def update
    @plan = Plan.find(params[:id])
    if @plan.update_attributes(plan_params)
      redirect_to @plan, :notice => "Your plan has been updated!"
    else
      render 'edit'
    end
  end

  private
  def plan_params
    params.require(:plan).permit(:name, :time, :restaurant_id, :restaurant)
  end
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/views/plans/_all_plans.html.erb
                        <div class="sidebar-widget">
                          <div class="Pricing-box bottom-box highlight">
                            
                             <div class="price-title spacing-box">
                                <h4>Upcoming Plans</h4>
                              </div>
                            <hr>
                            <ul>
                              <%plans.each do |plan|%>
                                <li><span class="bold-text">Plan Name:</span> <%=plan.name%></li>
                                <li><span class="bold-text">When:</span><%= plan.time.strftime("%B %d at %I:%M %p")%></li>
                                <li><span class="bold-text">Where:</span><%= plan.restaurant.name %></li>

                              <li><span class="bold-text">Who's In?</span></li>
                                <ul id="plan-users-<%=plan.id%>">
                                  <%plan.users.each do |user| %>
                                      <li><%=user.name%></li>
                                </ul>
                                  <%end%>
                                <div class="spacing-grid">
                                    <div id="button-section-<%=plan.id%>">
                                     <%=render partial: 'plans/button',
                                        locals: {in_plan: plan.users.include?(current_user), plan: plan}%>
                                          
                                    </div>
                                                
                                          

                                </div>
                                 _________________
                              <% end %>
                     
                                
                                </ul>
                                  
                          </div>
                         </div> 
                  

app/views/plans/_button.html.erb
<% if in_plan %>

    <%=link_to "Leave plan", leave_plan_path(plan), remote: true, :class => "btn btn-md btn-black", :method => 'DELETE'%>

<% else %>
    <%= link_to "Join", join_plan_path(plan), remote: true, :class => "btn btn-md btn-black"%>

<% end %>

<% if flash[:error]  %>
  <%= flash[:error]  %>

<% end %>

app/views/plans/_form.html.erb
<div class="sidebar-widget">
  <div class="Pricing-box">
      <div class="price-title spacing-box">
        <h4>Create a New Plan</h4>
      </div>

    <hr>
    <div class = "sidebar-form">
    <%= form_for(plan) do |f| %>

      <div class="name-field">
        <%= f.label :name %>
        <%= f.text_field :name %>
      </div>

      <div class="time-field">
        <%= f.label :time %>
        <%= f.time_field :time %>
      </div>

      <div class="date-field">
        <%= f.label :date %>
        <%= f.date_select :date %>
      </div>

      <div class="restaurant-field">
        <%= f.label :restaurant %>
        <%= f.collection_select :restaurant_id, Restaurant.all, :id, :name %>
      </div>
      </div>

      <div class="spacing-grid">
        <%= f.submit "Create Plan", class: 'btn btn-md btn-black'%>
      </div>
    <% end %>
  </div>
</div>

app/views/plans/_individual_plan.html.erb
<h2>Plan details</h2>
  <%# if plan.time == Date.current %>
  <%= render 'restaurants/map'%>
  
  <div>
    Name: <%=   @plan.name %><br>
    Time: <%=   @plan.time %><br>
    Restaurant: <%= link_to @plan.restaurant.name, restaurant_path(@plan.restaurant) %><br>
    Attendees: <%   @plan.users.each do |user|%>
        <%= user.name %>
    <%end%><br>
    Host: <%= @plan.host.name %><br>
    <% if @plan.host == current_user %>
    <%= link_to "Edit plan", edit_plan_path %>
    <% end %>
  </div>
  <%#end%>

app/views/plans/_plan_intake_form.html.erb
<h5>Enter your lunch plan to let others know and join</h5>

<%= form_for (@plan) do |f| %>

<div class="name-field">
  <%= f.label :name %>
  <%= f.text_field :name %>
</div>

<div class="time-field">
  <%= f.label :time %>
  <%= f.time_field :time %>
</div>

<div class="date-field">
  <%= f.label :date %>
  <%= f.date_select :date %>
</div>

<div class="restaurant-field">
  <%= f.label :restaurant %>
  <%= f.collection_select :restaurant_id, Restaurant.all, :id, :name %>

</div>

<%= f.submit "Create Plan" %>
<% end %>

app/views/plans/edit.html.erb
<%= render 'form' %>

app/views/plans/index.html.erb
<section class="ptb ptb-sm-30">
            <div class="container">
                <div class="row">
                    <div class="col-md-3 col-sm-4 mt-xs-30">
                      <%= render "plans/form", {plan: Plan.new } %>
                      <%= render "plans/all_plans", {plans: @plans} %>
                    </div>
                </div>
            </div>
</section>

<!-- 
<ul>
  <%@plans.each do |plan|%>
  <li>Name: <%=plan.name%></li>
  <li>You coming with?
    <%= link_to "Join", join_plan_path(plan), remote: true, :id => "join-#{plan.id}"%>
    <%=link_to "Leave plan", leave_plan_path(plan), remote: true, :id => "leave-#{plan.id}", :class => "hide_this", :method => 'DELETE'  %><span id="plan-status-<%=plan.id%>"></span>
  </li>
  <li>When:<%= plan.time.strftime("%B %d at %I:%M %p")%></li>
  <li>Where:<%= plan.restaurant.name %></li>
  <li>Users:</li>
    <ul id="plan-users-<%=plan.id%>">
      <% plan.users.each do |user| %>
        <li><%=user.name%></li>
      <%end%>
    </ul>
    <br>
    ------------------
    <br>
  <%end%>
</ul> -->

app/views/plans/join_plan.js.erb
  $("#plan-users-<%=@plan.id%>").append('<li><%=current_user.name%></li>' );
  $("#button-section-<%=@plan.id%>").html("<%= j render partial: 'button',
                                        locals: {in_plan: @in_plan, plan: @plan}%>");

app/views/plans/junk_code.html.erb
junk_code.html.erb


<h5>Create a New Plan</h5>

<section class="ptb ptb-sm-80">
            <div class="container">
                <div class="row">
                    <div class="col-md-3 col-sm-4 mt-xs-30">

                        <div class="sidebar-widget">
                            <h5>Product Categories</h5>
                            <hr>
                            <%= form_for(plan) do |f| %>

                              <div class="name-field">
                                <%= f.label :name %>
                                <%= f.text_field :name %>
                              </div>

                              <div class="time-field">
                                <%= f.label :time %>
                                <%= f.time_field :time %>
                              </div>

                              <div class="date-field">
                                <%= f.label :date %>
                                <%= f.date_select :date %>
                              </div>

                              <div class="restaurant-field">
                                <%= f.label :restaurant %>
                                <%= f.collection_select :restaurant_id, Restaurant.all, :id, :name %>

                              </div>

                              <%= f.submit "Create Plan" %>
                              <% end %>
                        </div>

                    </div>
                  </div>
                </div>
              </section>




              this upcoming plans works!


              
                        <div class="sidebar-widget">
                            <h5>Upcoming Plans</h5>
                            <hr>
                            <ul>
                              <%plans.each do |plan|%>
                              <li>Name: <%=plan.name%></li>
                              <li>You coming with?
                                <%= link_to "Join", join_plan_path(plan), remote: true, :id => "join-#{plan.id}"%>
                                <%=link_to "Leave plan", leave_plan_path(plan), remote: true, :id => "leave-#{plan.id}", :class => "hide_this", :method => 'DELETE'  %><span id="plan-status-<%=plan.id%>"></span>
                              </li>
                              <li>When:<%= plan.time.strftime("%B %d at %I:%M %p")%></li>
                              <li>Where:<%= plan.restaurant.name %></li>
                              <li>Users:</li>
                                <ul id="plan-users-<%=plan.id%>">
                                  <% plan.users.each do |user| %>
                                    <li><%=user.name%></li>
                                  <%end%>
                                </ul>
                                  <br>
                                  ------------------
                                  <br>
                                <%end%>
                                </ul>
                        </div>

app/views/plans/leave_plan.js.erb
$( "#plan-users-<%=@plan.id%> li:contains('<%=current_user.name%>')" ).remove();

$("#button-section-<%=@plan.id%>").html("<%= j render partial: 'button',
                                         locals: {in_plan: @in_plan, plan: @plan}%>");

app/views/plans/new.html.erb
<h1>Make a plan!</h1>
<br>
<br>
<br>


<%= render "plans/form", {plan: Plan.new} %>

app/views/plans/show.html.erb
<%= render 'individual_plan' %>