config/routes.rb
Rails.application.routes.draw do
  # root 'sessions#index'
  # root 'user_organizations#index'

  root 'welcome#index'

  resources :organizations
  resources :users
  resources :sessions
  resources :reviews
  resources :restaurants
  resources :plans

  resources :cuisines

  get 'login', :to => 'sessions#new'
  delete 'logout', :to => 'sessions#destroy'
  get 'signup', :to => 'users#new'
  get 'logged_in', :to => 'sessions#index'
  get 'join', :to => 'users#join'
  get '/:id/join-plan', :to => 'plans#join_plan', :as => 'join-plan'
  delete '/:id/leave_plan', :to => 'plans#leave_plan', :as => 'leave-plan'
  get 'add', :to => 'users#add'
  post 'join/', :to => 'users#join'
  get 'dashboard/', :to =>'users#dashboard'
  get '/:token/confirm_email/:id', :to => "organizations#confirm_email", as: '/confirm_email'
  delete '/:id/remove-user/:organization', :to => 'organizations#remove_user', :as => 'remove_user'
  post 'request_access/:id', :to => "users#request_access", as: "request_access"
  get '/:token/grant_access/:id', :to => "organizations#grant_access", as: '/grant_access'

end

app/views/layouts/_header.html.erb
<div class="links">
  <% if logged_in? %>
    <%= link_to "Log Out", logout_path, method: :delete %>
    <%= link_to "Dashboard", dashboard_path %>
    <%= link_to "Create New Organization", new_organization_path %>
    <%= link_to "Join Existing Organization", add_path %>
    <%= link_to "Make A New Plan", new_plan_path %>
    <%= link_to "Join A Plan", plans_path %>
    <%= link_to "Cuisines", cuisines_path %>
  <%else%>
    <%= link_to "Sign Up", signup_path %>
    <%= link_to "Sign In", login_path %>
  <%end%>
</div>

<% if logged_in? %>
  <%= image_tag current_user.avatar.url(:small) %>
  <%= current_user.name %>
  <%= link_to "Edit", edit_user_path(current_user), :class => "edit-user" %>
<%end%>

app/views/layouts/_home.html.erb
<!DOCTYPE html>
<html>
<head>
  <!-- From Rails -->
  <%= stylesheet_link_tag "application" %>
  <%= csrf_meta_tags %>
  <%= javascript_include_tag "application" %>

    <meta charset="utf-8" />
    <title>QuickByte</title>
    <meta name="description" content="" />
    <meta name="keywords" content="" />
    <meta name="author" content="nileforest">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0" />
    <!--[if IE]><meta http-equiv='X-UA-Compatible' content='IE=edge,chrome=1'><![endif]-->

    <!-- Favicone Icon -->
    <link rel="shortcut icon" type="image/x-icon" href="/assets/img/favicon.ico">
    <link rel="icon" type="image/png" href="/assets/img/favicon.png">
    <link rel="apple-touch-icon" href="/assets/img/favicon.png">

</head>

<body class="full-intro">

    <!-- Preloader -->
    <section id="preloader">
        <div class="loader" id="loader">
            <div class="loader-img"></div>
        </div>
    </section>
    <!-- End Preloader -->

    <!-- Sidemenu -->
    <section class="side-menu cbp-spmenu cbp-spmenu-vertical cbp-spmenu-right">
        <a class="menu-close toggle-menu menu-right push-body"><i class="ion ion-android-close"></i></a>
        <h5 class="white">Sign In</h5>
        <div class="sign-in">
            <input class="input-sm form-full" type="email" aria-required="true" id="email" name="email" placeholder="Email" value="" />
            <input class="input-sm form-full" type="password" aria-required="true" id="password" name="password" placeholder="Password" value="" />
            <input type="submit" class="btn btn-md btn-color-b form-full" value="Sign In" />
            <a>New Customer?</a>
        </div>
        <ul>
            <li><a target="_blank" href="index.html">Main Demo Page</a></li>
            <li><a href="home.html">Home Default</a></li>
            <li><a href="portfolio-grid-2col.html">Portfolio</a></li>
            <li><a href="login-register.html">Login & Signup</a></li>
            <li><a href="faq-1.html">FAQ</a></li>
            <li><a href="about-1.html">About</a></li>
            <li><a href="service-1.html">Service</a></li>
            <li><a href="blog-grid-3col.html">Blog</a></li>
            <li><a href="404-error-1.html">404 Error</a></li>
            <li><a href="shop-checkout.html">Shopping Cart</a></li>
            <li><a href="contact-1.html">Contact Us</a></li>
        </ul>
    </section>
    <!--End Sidemenu -->

    <!-- Search menu Top -->
    <section class=" top-search-bar cbp-spmenu cbp-spmenu-horizontal cbp-spmenu-top">
        <div class="container">
            <div class="search-wraper">
                <input type="text" class="input-sm form-full" placeholder="Search..." name="search" />
                <a class="search-bar-icon"><i class="fa fa-search"></i></a>
                <a class="bar-close toggle-menu menu-top push-body"><i class="ion ion-android-close"></i></a>
            </div>
        </div>
    </section>
    <!--End Search menu Top -->

    <!-- Site Wraper -->
    <div class="wrapper">

        <!-- HEADER -->
        <header class="header">
            <div class="container">

                <!-- logo -->
                <div class="logo light-color">
                    <a href="#">
                      <%= image_tag "img/logo-white.png", :class => "l-black" %>
                    </a>
                </div>
                <!--End logo-->


                <!-- Navigation Menu -->
                <nav class='navigation light-color'>
                    <ul>
                        <li class='light-color'>
                            <% if logged_in? %>
                                <%= link_to "Your Dashboard", dashboard_path, {:style=>'color:#FFFFFF;', :class => "light-color"} %>
                            <% else %>
                              <%= link_to "Login or Signup", login_path, {:style=>'color:#FFFFFF;', :class => "light-color"} %>
                            <% end %>
                        </li>                        
                    </ul>
                </nav>
                <!--End Navigation Menu -->

            </div>
        </header>
        <!-- END HEADER -->

        <!-- CONTENT --------------------------------------------------------------------------------->

        <!-- Intro Section -->
        <section class="hero">
            <!-- Hero Slider Section -->
            <div class="flexslider fullscreen-carousel hero-slider-1 parallax parallax-section1">
                <ul class="slides">
                    <li>
                        
                        <%= image_tag "img/full/11.jpg" %>
                        <div class="overlay-hero overlay-dark">
                            <div class="container caption-hero light-color">
                                <div class="inner-caption">

                                    <h2 class="h2">Welcome to QuickByte</h2>
                                    <p class="lead">Create a community for grabbing a quick bite.</p>

                                </div>
                            </div>
                        </div>
                    </li>
                    <li>
                        <%= image_tag "img/full/20.jpg" %>
                        <div class="overlay-hero overlay-dark">
                            <div class="container caption-hero light-color">
                                <div class="inner-caption">
                                    <h2 class="h2">Because who has time to wait?</h2>
                                    <p class="lead">We carry a passion for good food fast.</p>
                                </div>
                            </div>
                        </div>
                    </li>
                    <li>
                        <%= image_tag "img/full/02.jpg" %>
                        <div class="overlay-hero overlay-dark">
                            <div class="container caption-hero light-color">
                                <div class="inner-caption">
                                    <h2 class="h2">Even if it's fast it might as well be good.</h2>
                                    <p class="lead">See peer reviews and wait times.</p>
                                </div>
                            </div>
                        </div>
                    </li>

                    <li>
                        <%= image_tag "img/full/18.jpg" %>
                        <div class="overlay-hero overlay-dark">
                            <div class="container caption-hero light-color">
                                <div class="inner-caption">
                                    <h2 class="h2">Build a food community</h2>
                                    <p class="lead">Make lunch plans with your friends or coworkers.</p>
                                </div>
                            </div>
                        </div>
                    </li>
                </ul>
            </div>
            <!-- End Hero Slider Section -->
        </section>
        <div class="clearfix"></div>
        <!-- End Intro Section -->
        <!-- END CONTENT ---------------------------------------------------------------------------->
    </div>
    <!-- Site Wraper End -->



</body>
</html>

app/views/layouts/_maps.html.erb
_maps.html.erb

app/views/layouts/_searchmenu.html.erb
<section class=" top-search-bar cbp-spmenu cbp-spmenu-horizontal cbp-spmenu-top">
    <div class="container">
        <div class="search-wraper">
            <input type="text" class="input-sm form-full" placeholder="Search..." name="search" />
            <a class="search-bar-icon"><i class="fa fa-search"></i></a>
            <a class="bar-close toggle-menu menu-top push-body"><i class="ion ion-android-close"></i></a>
        </div>
    </div>
</section>

app/views/layouts/_sidebar.html.erb
<div class="sidebar-widget">
  <% current_user.organizations.each do |organization| %>
    <div >
      <%= link_to organization.name, organization_path(organization.id), :class => "btn btn-md btn-black" %><br><br>
    </div>
  <%end%>    

</div>

app/views/layouts/_sidebar_for_plans.html.erb
<section class="ptb ptb-sm-80">
            <div class="container">
                <div class="row">
                    <div class="col-md-3 col-sm-4 mt-xs-30">

  

                        <div class="sidebar-widget">
                            <h5>Recent Post</h5>
                            <hr>
                            
<h5>Enter your lunch plan to let others know and join</h5>

<%= form_for (plan) do |f| %>

<div class="name-field">
  <%= f.label :name %>
  <%= f.text_field :name %>
</div>

<div class="time-field">
  <%= f.label :time %>
  <%= f.time_field :time %>
</div>

<div class="date-field">
  <%= f.label :date %>
  <%= f.date_select :date %>
</div>

<div class="restaurant-field">
  <%= f.label :restaurant %>
  <%= f.collection_select :restaurant_id, Restaurant.all, :id, :name %>

</div>

<%= f.submit "Create Plan" %>
<% end %>

                        </div>

                        <div class="sidebar-widget">
                            <h5>popular Tags</h5>
                            <hr>
                            <ul class="widget-tag">
                                <li><a>Art</a></li>
                                <li><a>Business</a></li>
                                <li><a>Design</a></li>
                                <li><a>Graphic</a></li>
                                <li><a>fashion</a></li>
                                <li><a>Model</a></li>
                                <li><a>Photography</a></li>
                            </ul>
                        </div>

                    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <!-- From Rails -->
  <%= stylesheet_link_tag "application" %>
  <%= csrf_meta_tags %>
  <%= javascript_include_tag "application" %>
  <script src="//maps.google.com/maps/api/js?v=3.18&sensor=false&client=&key=<%ENV['GOOGLE_KEY']%>&libraries=geometry&language=&hl=&region="></script>
  <script src="//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js"></script>
  <script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/infobox/1.1.9/src/infobox_packed.js' type='text/javascript'></script>
  <script src='//google-maps-utility-library-v3.googlecode.com/svn/trunk/richmarker/src/richmarker-compiled.js' type='text/javascript'></script>

    <meta charset="utf-8" />
    <title>QuickByte</title>
    <meta name="description" content="" />
    <meta name="keywords" content="" />
    <meta name="author" content="nileforest">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0" />
    <!--[if IE]><meta http-equiv='X-UA-Compatible' content='IE=edge,chrome=1'><![endif]-->

    <!-- Favicone Icon -->
    <link rel="shortcut icon" type="image/x-icon" href="/assets/img/favicon.ico">
    <link rel="icon" type="image/png" href="/assets/img/favicon.png">
    <link rel="apple-touch-icon" href="/assets/img/favicon.png">




</head>

<body class="full-intro">

    <!-- Preloader -->
    <section id="preloader">
        <div class="loader" id="loader">
            <div class="loader-img"></div>
        </div>
    </section>
    <!-- End Preloader -->

    <!-- Sidemenu -->
    <section class="side-menu cbp-spmenu cbp-spmenu-vertical cbp-spmenu-right">
        <a class="menu-close toggle-menu menu-right push-body"><i class="ion ion-android-close"></i></a>
        <h5 class="white">Sign In</h5>
        <div class="sign-in">
            <input class="input-sm form-full" type="email" aria-required="true" id="email" name="email" placeholder="Email" value="" />
            <input class="input-sm form-full" type="password" aria-required="true" id="password" name="password" placeholder="Password" value="" />
            <input type="submit" class="btn btn-md btn-color-b form-full" value="Sign In" />
            <a>New Customer?</a>
        </div>
        <ul>
            <li><a target="_blank" href="index.html">Main Demo Page</a></li>
            <li><a href="home.html">Home Default</a></li>
            <li><a href="portfolio-grid-2col.html">Portfolio</a></li>
            <li><a href="login-register.html">Login & Signup</a></li>
            <li><a href="faq-1.html">FAQ</a></li>
            <li><a href="about-1.html">About</a></li>
            <li><a href="service-1.html">Service</a></li>
            <li><a href="blog-grid-3col.html">Blog</a></li>
            <li><a href="404-error-1.html">404 Error</a></li>
            <li><a href="shop-checkout.html">Shopping Cart</a></li>
            <li><a href="contact-1.html">Contact Us</a></li>
        </ul>
    </section>
    <!--End Sidemenu -->

    <!-- Search menu Top -->
    <section class=" top-search-bar cbp-spmenu cbp-spmenu-horizontal cbp-spmenu-top">
        <div class="container">
            <div class="search-wraper">
                <input type="text" class="input-sm form-full" placeholder="Search..." name="search" />
                <a class="search-bar-icon"><i class="fa fa-search"></i></a>
                <a class="bar-close toggle-menu menu-top push-body"><i class="ion ion-android-close"></i></a>
            </div>
        </div>
    </section>
    <!--End Search menu Top -->

    <!-- Site Wraper -->
    <div class="wrapper">

        <!-- HEADER -->
        <header class="header">
            <div class="container">

                <!-- logo -->
                <div class="logo">
                    <a href="#">
                        <%= image_tag "img/logo-black.png", :class => "l-black" %>
                    </a>
                </div>
                <!--End logo-->

                <!-- Rightside Menu (Search, Cart, Bart icon) -->
                <div class="side-menu-btn">
                    <ul>
                        <!-- Avatar -->
                        <li class="">
                            <% if logged_in? %>
                              <%= image_tag current_user.avatar.url(:thumb) %>
                              <%= link_to current_user.name , edit_user_path(current_user), :class => "edit-user" %>
                            <%end%>
                        </li>
                        <!-- End Avatar Icon -->

                    </ul>
                </div>
                <!-- End Rightside Menu -->

                <!-- Navigation Menu -->
            <% if logged_in? %>
                <nav class='navigation'>
                    <ul>
                        <li>
                            <a href="#">Actions</a>
                            <!-- Nav Dropdown -->
                            <ul class="nav-dropdown">
                                <li>
                                    <%= link_to "Join Organization", add_path %>
                                </li>
                                <li>
                                    <%= link_to "Create Organization", new_organization_path %>
                                </li>
                                <li>
                                    <%= link_to "Make A New Plan", new_plan_path %>
                                </li>

                            </ul>
                            <!-- End Nav Dropdown -->
                        </li>


                        <li>
                            <%= link_to "Dashboard", dashboard_path %>
                        </li>
                        <li>
                            <%= link_to "Log Out", logout_path, method: :delete %>
                        </li>
                    </ul>
                </nav>
            <% end %>
                <!--End Navigation Menu -->

            </div>
        </header>
        <!-- END HEADER -->


        <!-- Blank Section -->

        <section class="ptb ptb-sm-80 container">
            <!-- Remove tags----(<br />) -->
            <%= yield %>
            <!-- Remove tags -->

        </section>
        <!-- End Blank Section -->

        <!-- End CONTENT ------------------------------------------------------------------------------>

        <!-- FOOTER -->
        <footer class="footer pt-50">
            <div class="container">
                <div class="row mb-30">
                    <!-- Logo -->
                    <div class="col-md-3 col-sm-3 col-xs-12 mb-xs-30">
                        <a class="footer-logo" href="home.html">
                            <h2><%= link_to "QuickByte.", root_path %></h2>
                    </div>
                    <!-- Logo -->

                    <!-- Newsletter -->
                    <div class="col-md-4 col-sm-5 col-xs-12 mb-xs-30">
                        <div class="newsletter">

                        </div>
                    </div>
                    <!-- End Newsletter -->

                    <!-- Social -->
                    <div class="col-md-3 col-md-offset-2 col-sm-4 col-xs-12">
                        <ul class="social">

                        </ul>
                    </div>
                    <!-- End Social -->
                </div>
                <!--Footer Info -->
                <div class="row footer-info mb-60">
                    <div class="col-md-3 col-sm-12 col-xs-12 mb-sm-30">
                        <p class="mb-xs-0">QuickByte is a web app designed for lunchtime discovery and collaboration.</p>
                    </div>
                    <div class="col-md-3 col-sm-6 col-xs-12 mb-sm-30 mb-xs-0">
                        <ul class="link">
                            <li><%= link_to "My Organizations", organizations_path %></li>
                            <li><%= link_to "All Plans", plans_path %></li>
                            <li><%= link_to "My Coworkers", users_path %></li>
                        </ul>
                    </div>
                    <div class="col-md-3 col-sm-6 col-xs-12 mb-sm-30">
                        <ul class="link">
                            <li><%= link_to "My Info", users_path %></li>
                            <li><%= link_to "My Public Bio ", organizations_path %></li>
                        </ul>
                    </div>
                    <div class="col-md-3 col-sm-12 col-xs-12">
                        <p>The Flatiron School,
                        11 Broadway,
                        NY, NY 10004</p>
                        <ul class="link-small">
                            <li><a href="github.com/littlejeon/quick_byte"><i class="fa fa-github"></i>  Check Out Our Code Ya'll</a></li>
                        </ul>
                    </div>
                </div>
                <!-- End Footer Info -->
            </div>

            <hr />

            <!-- Copyright Bar -->
            <section class="copyright ptb-60">
                <div class="container">
                    <p class="">
                        © 2016 <a><b>QuickByte</b></a>. All Rights Reserved.
                        Made with <i class="fa fa-heart"></i> at the Flatiron School.
                        <br />
                    </p>
                </div>
            </section>
            <!-- End Copyright Bar -->

        </footer>
        <!-- END FOOTER -->

        <!-- Scroll Top -->
        <a class="scroll-top">
            <i class="fa fa-angle-double-up"></i>
        </a>
        <!-- End Scroll Top -->

    </div>
    <!-- Site Wraper End -->


    <!-- JS -->


</body>
</html>